"use client";

import dynamic from 'next/dynamic';
import { useMemo } from 'react';

// Plotly needs to be dynamically imported with SSR disabled because it relies heavily on the window object
const Plot = dynamic(() => import('react-plotly.js'), { ssr: false });

interface VizProps {
  spec: any; // The JSON specification generated by the Python backend (viz_builder.py)
}

/**
 * Renders dynamic charts (Depth Profiles, T-S Diagrams, Time Series) 
 * directly from the backend's generated Plotly JSON specification.
 */
export default function FloatDataViz({ spec }: VizProps) {
  // Apply our global ARGO dark theme overrides onto whatever the backend sends
  const layout = useMemo(() => {
    if (!spec || !spec.layout) return {};
    
    return {
      ...spec.layout,
      paper_bgcolor: 'transparent', // Make background glassmorphic
      plot_bgcolor: 'transparent',
      font: {
        family: 'var(--font-inter), sans-serif',
        color: '#E2E8F0'
      },
      xaxis: {
        ...spec.layout.xaxis,
        gridcolor: 'rgba(255,255,255,0.1)',
        zerolinecolor: 'rgba(0,240,255,0.3)', // argo.cyan
      },
      yaxis: {
        ...spec.layout.yaxis,
        gridcolor: 'rgba(255,255,255,0.1)',
        zerolinecolor: 'rgba(0,240,255,0.3)',
      },
      margin: { l: 50, r: 20, t: 40, b: 40 },
    };
  }, [spec]);

  if (!spec || !spec.data) return null;

  return (
    <div className="w-full h-64 mt-3 bg-black/40 rounded-xl border border-white/10 p-2 overflow-hidden relative group">
      <Plot
        data={spec.data}
        layout={layout}
        config={{
          responsive: true,
          displayModeBar: false, // Cleaner UI
        }}
        style={{ width: '100%', height: '100%' }}
        className="viz-plot"
      />
      {/* Decorative corner accents */}
      <div className="absolute top-0 left-0 w-2 h-2 border-t border-l border-argo-cyan opacity-50 m-2 pointer-events-none" />
      <div className="absolute bottom-0 right-0 w-2 h-2 border-b border-r border-argo-cyan opacity-50 m-2 pointer-events-none" />
    </div>
  );
}
